FROM python:3.11-slim

#set working directory
WORKDIR /colonoscopy-triage-v2

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY streamlit_app ./streamlit_app

CMD ["streamlit", "run", "streamlit_app/ui_app.py", "--server.port=8501", "--server.address=0.0.0.0"]